Repository arrayfire/arrayfire, pull requests merged in 2018-04, with the labels that each got.

#2101 Simplify ArrayFireConfig script and improve documentation.
  CMakeLists.txt
  CMakeModules/ArrayFireConfig.cmake.in
  CMakeModules/InternalUtils.cmake
  src/backend/cpu/CMakeLists.txt
  src/backend/cuda/CMakeLists.txt
  src/backend/opencl/CMakeLists.txt
Labels: build

#2103 Create installers with dependences only when AF_INSTALL_STANDALONE is set
  CMakeLists.txt
  src/api/c/CMakeLists.txt
  src/backend/common/CMakeLists.txt
  src/backend/cuda/CMakeLists.txt
Labels: build

#2107 Mark cmake MKL DLL varaibles as advanced
  CMakeModules/FindMKL.cmake
Labels: build

#2109 Fix cpack GUI installer components dependencies
  CMakeLists.txt
  CMakeModules/CPackConfig.cmake
  src/api/c/CMakeLists.txt
  src/backend/common/CMakeLists.txt
Labels: build

#2111 Reorganize GUI installer components hierarchy
  CMakeModules/CPackConfig.cmake
Labels: build

#2114 Install correct OpenCL ICD file on Windows
  src/backend/opencl/CMakeLists.txt
Labels: Windows, build

#2095 Miscellaneous changes for 3.6 release
  docs/pages/install.md
  docs/pages/using_on_linux.md
  docs/pages/using_on_osx.md
  docs/pages/using_on_windows.md
  examples/CMakeLists.txt
Labels: Documentation, examples

#2124 Move nativeFree calls outside of the memory_mutex to avoid deadlock
  src/backend/common/MemoryManager.hpp
Labels: backport

#2126 Disable ignored-attributes warnings in the OpenCL backend
  src/backend/opencl/CMakeLists.txt
  src/backend/opencl/kernel/scan_by_key/CMakeLists.txt
  src/backend/opencl/kernel/sort_by_key/CMakeLists.txt
Labels: build

#2138 Fix superscript tags in release notes
  docs/pages/release_notes.md
Labels: Documentation, fix

#2141 Fix cmake crash with vcpkg package manager
  CMakeModules/ArrayFireConfig.cmake.in
  CMakeModules/ArrayFireExampleOverloads.cmake
  examples/CMakeLists.txt
  test/CMakeLists.txt
Labels: build, fix
