Repository arrayfire/arrayfire, pull requests merged in 2018-05, with the labels that each got.

#2147 Add Tegra toolchain support
  CMakeLists.txt
  CMakeModules/TegraCrossToolchain.cmake
Labels: build

#2123 Remove nvcc-gcc version compatibility check
  src/backend/cuda/CMakeLists.txt
Labels: ready to merge

#2149 Fix variable const qualifiers in blas files
  src/backend/cpu/blas.cpp
  src/backend/cpu/sparse_blas.cpp
Labels: Linux, build, fix

#2150 Disable hunter use by forge from ArrayFire
  CMakeModules/build_forge.cmake
Labels: build

#2170 Add libdl when building with FreeImage
  src/api/c/CMakeLists.txt
Labels: build
