Repository arrayfire/arrayfire, pull requests merged in 2018-06, with the labels that each got.

#2174 Performance improvments to CPU Anisotropic Diffusion
  src/backend/cpu/kernel/anisotropic_diffusion.hpp
  src/backend/cuda/kernel/anisotropic_diffusion.hpp
  src/backend/opencl/kernel/anisotropic_diffusion.cl
Labels: perf

#2175 Fix host leak when assigning indexed array to another indexed array
  src/api/cpp/array.cpp
Labels: bug, fix

#2189 Fix input validation in DeviceManager::setActiveDevice
  src/backend/cuda/platform.cpp
Labels: CUDA, fix

#2182 Check for unsupported cards on a given cuda runtime
  src/backend/cuda/platform.cpp
  test/info.cpp
  test/solve_dense.cpp
  test/threading.cpp
Labels: fix

#2185 Defer fft normalization to post transform stage
  src/api/c/fft_common.hpp
Labels: fix

#2153 Fix checks in af::seq() & indexing/assignment functions
  include/af/index.h
  src/api/c/array.cpp
  src/api/c/assign.cpp
  src/api/c/handle.hpp
  src/api/c/index.cpp
  src/api/c/indexing_common.hpp
  src/api/c/moddims.cpp
  src/api/cpp/seq.cpp
  src/backend/cpu/index.cpp
  src/backend/cpu/lookup.cpp
  src/backend/cpu/lookup.hpp
  src/backend/cuda/lookup.cu
  src/backend/cuda/lookup.hpp
  src/backend/opencl/lookup.cpp
  src/backend/opencl/lookup.hpp
  test/assign.cpp
  test/index.cpp
Labels: fix

#2202 Fix leak in cuda JIT by deleting link state and nvrtc program
  src/backend/cuda/jit.cpp
Labels: fix

#2207 Fix window cell indexing in graphics
  include/af/graphics.h
  src/api/c/image.cpp
  src/api/c/plot.cpp
  src/api/c/surface.cpp
  src/api/c/vector_field.cpp
Labels: fix
