Repository arrayfire/arrayfire, pull requests merged in 2018-02, with the labels that each got.

#2053 Fix AF_API_VERSION value in doxygen config file
  docs/doxygen.mk
Labels: Documentation, fix

#2058 Fix assertions for select test failures
  test/select.cpp
Labels: test

#2055 Use a separate FindMKL script instead of current version
  CMakeLists.txt
  CMakeModules/FindCBLAS.cmake
  CMakeModules/FindFFTW.cmake
  CMakeModules/FindMKL.cmake
  CMakeModules/platform.cmake
  src/api/unified/CMakeLists.txt
  src/backend/common/CMakeLists.txt
  src/backend/cpu/CMakeLists.txt
  src/backend/opencl/CMakeLists.txt
Labels: build, in-progress
