Repository arrayfire/arrayfire, pull requests merged in 2018-07, with the labels that each got.

#2223 Fix NSIS dll path used for modifying PATH
  CMakeModules/nsis/NSIS.template.in
Labels: Windows, build

#2226 Fix include dirs command in unified cmake script
  src/api/unified/CMakeLists.txt
Labels: build, fix

#2227 Fix include dirs command in unified cmake script
  src/api/unified/CMakeLists.txt
Labels: backport

#2230 Fix grid based indexing calculation for histogram
  src/api/c/hist.cpp
Labels: fix

#1881 FEAT: Image Deconvolution Functions
  docs/details/image.dox
  examples/image_processing/CMakeLists.txt
  examples/image_processing/deconvolution.cpp
  include/af/defines.h
  include/af/image.h
  src/api/c/CMakeLists.txt
  src/api/c/deconvolution.cpp
  src/api/cpp/CMakeLists.txt
  src/api/cpp/deconvolution.cpp
  src/api/unified/image.cpp
  src/backend/common/dispatch.hpp
  src/backend/cpu/CMakeLists.txt
  src/backend/cpu/copy.hpp
  src/backend/cpu/kernel/pad_array_borders.hpp
  src/backend/cpu/padarray.cpp
  src/backend/cuda/CMakeLists.txt
  src/backend/cuda/copy.hpp
  src/backend/cuda/kernel/pad_array_borders.hpp
  src/backend/cuda/pad_array_borders.cu
  src/backend/opencl/CMakeLists.txt
  src/backend/opencl/copy.hpp
  src/backend/opencl/kernel/pad_array_borders.cl
  src/backend/opencl/kernel/pad_array_borders.hpp
  test/CMakeLists.txt
  test/inverse_deconv.cpp
  test/iterative_deconv.cpp
  test/testHelpers.hpp
Labels: feature, ready to merge

#2243 Add batching support for cond argument in select; Batching Tests
  src/api/c/select.cpp
  src/backend/cpu/kernel/select.hpp
  test/select.cpp
Labels: feature

#2242 Fix mem leaks in deconvolution tests
  src/api/c/deconvolution.cpp
  src/backend/cpu/copy.hpp
  test/inverse_deconv.cpp
  test/iterative_deconv.cpp
Labels: fix, test

#2252 Refactor sign macro internally
  src/api/c/optypes.hpp
  src/api/c/unary.cpp
  src/backend/cpu/unary.hpp
  src/backend/cuda/kernel/jit.cuh
  src/backend/cuda/unary.hpp
  src/backend/opencl/kernel/jit.cl
  src/backend/opencl/unary.hpp
Labels: fix
