Repository arrayfire/arrayfire, pull requests merged in 2020-08, with the labels that each got.

#2982 Add min driver versions for CUDA 11
  src/backend/cuda/device_manager.cpp
Labels: fix

#2983 Replace underscores with dashes in package names
  CMakeModules/CPackConfig.cmake
Labels: fix, installer

#2991 Fix failure with git apply after make clean
  CMakeModules/build_CLBlast.cmake
  CMakeModules/clblast_program_getIR.patch
Labels: build

#2990 Build Unified backend without OpenCL or CUDA installed if necessary
  src/api/unified/CMakeLists.txt
Labels: build

#2988 Use sourceforge to download doxygen
  .github/workflows/docs_build.yml
Labels: build

#2997 Create a more portable macro that disables deprecated warnings
  src/api/cpp/device.cpp
  src/api/unified/CMakeLists.txt
  src/api/unified/device.cpp
  src/api/unified/graphics.cpp
  src/api/unified/statistics.cpp
  src/backend/common/deprecated.hpp
  src/backend/opencl/cl2hpp.hpp
  src/backend/opencl/kernel/regions.hpp
  src/backend/opencl/kernel/sift_nonfree.hpp
  src/backend/opencl/kernel/sort.hpp
  src/backend/opencl/kernel/sort_by_key_impl.hpp
  src/backend/opencl/set.cpp
  test/random.cpp
Labels: build
