Repository arrayfire/arrayfire, pull requests merged in 2020-10, with the labels that each got.

#3022 Fix features copy constructor for multithreaded usage
  include/af/features.h
  src/api/cpp/features.cpp
Labels: fix

#3024 Fix input ndims check for regions function
  src/api/c/regions.cpp
Labels: fix

#3030 Update GitHub workflows away from set-env
  .github/workflows/cpu_build.yml
  .github/workflows/release_src_artifact.yml
Labels: build

#2999 Update v3.8 release notes and add v3.7.3 release notes to it
  docs/pages/release_notes.md
Labels: Documentation, release

#3025 Add version info resource file for Window build
  CMakeLists.txt
  CMakeModules/generate_product_version.cmake
  CMakeModules/version_info.rc.in
  src/api/unified/CMakeLists.txt
  src/backend/cpu/CMakeLists.txt
  src/backend/cuda/CMakeLists.txt
  src/backend/opencl/CMakeLists.txt
Labels: build, improvement

#3027 Fix lapack support check in CPU/OpenCL backend CMakeLists
  src/backend/cpu/CMakeLists.txt
  src/backend/opencl/CMakeLists.txt
Labels: build, fix

#3028 Fix function name typo in timing tutorial
  docs/pages/timing.md
Labels: Documentation, fix
