Repository arrayfire/arrayfire, pull requests merged in 2021-05, with the labels that each got.

#3125 Add CUDA 11.3 max toolkit compute and driver versions
  src/backend/cuda/device_manager.cpp
Labels: CUDA

#3127 Use CL fill buffer instead of host allocation in csrmm kernel
  src/backend/opencl/kernel/csrmm.hpp
Labels: OpenCL, improvement, internal

#3129 Add missing batch support check in sparse-dense arith ops
  src/api/c/binary.cpp
Labels: fix

#3130 Write array patch
  src/api/c/array.cpp
Labels: fix

#3136 Mark advanced build options reflecting the same in cmake
  CMakeLists.txt
Labels: build, improvement

#3137 CMake presets to enable faster development cmake setup
  CMakePresets.json
Labels: build, improvement

#3131 Increase error tolerance to 0.07 for convolve tests
  test/convolve.cpp
Labels: internal

#3039 Reduce synchronized initialization of OpenCL Buffers
  src/backend/opencl/Kernel.cpp
  src/backend/opencl/kernel/fast.hpp
  src/backend/opencl/kernel/harris.hpp
  src/backend/opencl/kernel/orb.hpp
  src/backend/opencl/kernel/regions.hpp
  src/backend/opencl/kernel/sparse.hpp
  src/backend/opencl/kernel/sparse_arith.hpp
  src/backend/opencl/kernel/susan.hpp
Labels: fix, perf

#3119 vcpkg manifest file for ease of development; support to use as many vcpkg ports as possible
  .github/workflows/docs_build.yml
  .github/workflows/unix_cpu_build.yml
  .github/workflows/win_cpu_build.yml
  CMakeLists.txt
  CMakeModules/AF_vcpkg_options.cmake
  CMakeModules/AFconfigure_forge_dep.cmake
  CMakeModules/build_CLBlast.cmake
  src/backend/common/CMakeLists.txt
  src/backend/opencl/kernel/scan_by_key/CMakeLists.txt
  src/backend/opencl/kernel/sort_by_key/CMakeLists.txt
  vcpkg.json
Labels: build, improvement
