Repository arrayfire/arrayfire, pull requests merged in 2021-03, with the labels that each got.

#3102 Remove leftover clblas references from licenses & codebase
  CMakeModules/CPackConfig.cmake
  src/backend/opencl/CMakeLists.txt
  src/backend/opencl/err_clblas.hpp
Labels: internal

#3106 Fix glad add_subdirectory to fix out of tree builds
  CMakeLists.txt
Labels: build, fix

#3105 Fix for CUDA 11 nvrtc-builtins shared lib packaging
  src/backend/cuda/CMakeLists.txt
Labels: Linux, fix, installer

#3108 Change to reflect BOOST removal from gh action images
  .github/workflows/docs_build.yml
Labels: ci, fix

#3111 OPT: Optimize indexing using dynamic thread block sizes.
  src/backend/cuda/kernel/index.hpp
  src/backend/opencl/kernel/index.hpp
Labels: perf
